#!/usr/bin/env python3
import re
import os
from pathlib import Path

EMOJI_PATTERN = re.compile(
    "[\U0001F300-\U0001F6FF\U0001F900-\U0001F9FF\u2600-\u26FF\u2700-\u27BF]")
DECORATIVE_PATTERN = re.compile(r"^\s*#\s*[-=*_]{3,}.*$")
AI_TAGS_PATTERN = re.compile(r"\b(ai|assistant|generated by|copilot|emoji)\b", re.IGNORECASE)
SHORT_DECOR_PATTERN = re.compile(r"^\s*#\s*[-]{2,}\s*$")

ROOT = Path(__file__).resolve().parents[1]
TARGET_DIR = ROOT / 'Backend'

candidates = {}

for p in sorted(TARGET_DIR.glob('*.py')):
    rel = p.relative_to(ROOT)
    lines = p.read_text(encoding='utf-8', errors='replace').splitlines()
    found = []
    for i, line in enumerate(lines, start=1):
        s = line.strip()
        if not s.startswith('#'):
            continue
        # full-line comment only (skip inline comments after code)
        if re.match(r"^\s*#\s*[^\w\-\s].*|^\s*#\s*$", line):
            # comments starting with non-word or empty
            found.append((i, line))
            continue
        if EMOJI_PATTERN.search(line):
            found.append((i, line))
            continue
        if DECORATIVE_PATTERN.match(line) or SHORT_DECOR_PATTERN.match(line):
            found.append((i, line))
            continue
        if AI_TAGS_PATTERN.search(line):
            found.append((i, line))
            continue
        # very short comments (<=3 words) that look like section headers
        words = re.findall(r"\w+", line)
        if len(words) <= 3 and len(line.strip('#').strip()) <= 40 and re.search(r"\b(config|setup|utils|helpers|app|start|end|note|important)\b", line, re.IGNORECASE):
            found.append((i, line))
            continue
    if found:
        candidates[str(rel)] = found

if not candidates:
    print('No candidate AI/decorative comments found.')
else:
    total = sum(len(v) for v in candidates.values())
    print(f'Found {total} candidate comment lines in {len(candidates)} files:\n')
    for fname, items in candidates.items():
        print(f'== {fname} ==')
        for ln, txt in items:
            print(f'{ln:4d}: {txt.rstrip()}')
        print()

# Also write a JSON report for automated use
try:
    import json
    (ROOT / 'scripts' / 'find_ai_comments_report.json').write_text(json.dumps(candidates, ensure_ascii=False, indent=2), encoding='utf-8')
except Exception:
    pass
